name: API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Check if the renthub directory exists
            if [ -d "renthub" ]; then
              echo "renthub directory exists."
              cd renthub
              # Check if the accommodation directory exists
              if [ -d "accommodation" ]; then
                echo "Repository exists. Pulling latest changes..."
                cd accommodation
                git pull origin main
              else
                echo "Repository does not exist. Cloning repository..."
                git clone git@github.com:RentHubUZ/accommodation.git
                cd accommodation
              fi
            else
              echo "renthub directory does not exist. Creating directory..."
              mkdir renthub
              cd renthub
              echo "Cloning repository..."
              git clone git@github.com:RentHubUZ/accommodation.git
              cd accommodation
            fi

            # Stop and remove existing Docker containers
            docker compose down || true

            # Build and start Docker containers
            docker compose up -d